name: Metrics
on:
  schedule: [{cron: "0 12 * * *"}]  # atualiza todos os dias ao meio-dia
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_ignored: html
          plugin_languages_threshold: 0%
          plugin_languages_details: percentage
          config_timezone: America/Sao_Paulo
